workflows:
  build_varietas:
    name: Build Varietas APK
    environment:
      flutter: stable
      vars:
        FLUTTER_BUILD_RELEASE: true
    scripts:
      - name: Ensure Flutter project structure
        script: |
          if [ ! -d "android" ]; then
            echo "android folder missing — generating with flutter create ."
            flutter create .
          fi
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-shrink
    publishing:
      scripts:
        - name: APK Output
          script: |
            echo "APK generated here:"
            echo "build/app/outputs/flutter-apk/app-release.apk"
            ls -la build/app/outputs/flutter-apk || true
